# Configuración por defecto
spring:
  application:
    name: nequi-api
  profiles:
    active: default

aws:
  dynamodb:
    region: us-east-1
    access-key: default-access-key
    secret-key: default-secret-key
